### ISSUE TITLE
Updates with the newer upgrade card icons?

### ISSUE THREAD

**Issue by Sevcav** [Owen-A/Legion-font#1]
Hi mate, Your work has been great! I use it in a Legion Card maker power point template by Ryan Evans.

Are you planning on making any updates with emplacement generator,  special forces config, and heavy crew upgrade icons?

If not, no worries, maybe I can figure out how you used Font Forge, and can help contribute. This would require some reverse engineering and learning on my part.

 I can, but if you were planning on updating the font  with your proven methods, then awesome, and I wouldn't mess things up :)

**Comment by shiftregister-vg** [comment]
Would love to see an update to this (unless there is a replacement to this out there).

**Comment by Owen-A** [comment]
I stopped playing Legion so this fell by the wayside. If I have time I might try and update but I'm more than happy to approve submissions by others too.

**Comment by shiftregister-vg** [comment]
I would be willing to update it.  How did you go about creating the font face?  I'm pretty inexperienced in that field.

**Comment by Owen-A** [comment]
> I would be willing to update it. How did you go about creating the font face? I'm pretty inexperienced in that field.

I used FontForge. You can, erm, borrow some of them from the pdfs that FFG put out (e.g. rules updates) as the font faces are in part embedded in them. Others I had to create (tracing mostly) with a vector graphics program.

I was new to FontForge, but it is not that hard if you gave any graphics background

**Comment by lyerelian** [comment]
Updated the file with the Crew, Armament, and Generator upgrade, Operative unit icon, and increased the size of the melee icon.
